require_relative 'ast/node'
require_relative 'ast/program'
require_relative 'ast/block'
require_relative 'ast/type'

# Statement nodes
require_relative 'ast/statement'
require_relative 'ast/assignment_statement'
require_relative 'ast/break_statement'
require_relative 'ast/cast_statement'
require_relative 'ast/condition_statement'
require_relative 'ast/declaration_statement'
require_relative 'ast/expression_statement'
require_relative 'ast/function_statement'
require_relative 'ast/input_statement'
require_relative 'ast/loop_statement'
require_relative 'ast/print_statement'
require_relative 'ast/return_statement'
require_relative 'ast/switch_statement'
require_relative 'ast/else_if'
require_relative 'ast/case'
require_relative 'ast/loop_update'
require_relative 'ast/loop_guard'

# Expression nodes
require_relative 'ast/expr'
require_relative 'ast/cast_expr'
require_relative 'ast/constant_expr'
require_relative 'ast/variable_expr'
require_relative 'ast/func_call_expr'
require_relative 'ast/unary_op_expr'
require_relative 'ast/binary_op_expr'
require_relative 'ast/nary_op_expr'
